# Generated by Django 4.0.6 on 2022-07-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
