# Generated by Django 4.0.6 on 2022-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания продукта'),
        ),
    ]
