# Generated by Django 4.0.6 on 2022-07-14 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('description', models.CharField(max_length=150, verbose_name='Описание продукта')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='Дата создания продукта')),
                ('picture', models.ImageField(blank=True, max_length=900, upload_to='images/', verbose_name='Картинка продукта')),
                ('price', models.IntegerField(verbose_name='Цена продукта')),
            ],
            options={
                'unique_together': {('id', 'title')},
            },
        ),
    ]
